<a href="https://colab.research.google.com/github/Emmanuel10701/vite_practical/blob/main/tutorials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
matrix=np.array([[3,4],[0,5]])

tr = matrix.T
print(tr)
transpose = np.transpose(matrix)
print(matrix)
print(transpose)
det = np.linalg.det(matrix)
print(det)
detTasnpose = np.linalg.det(transpose)
print(detTasnpose)


dotProductOfAATraspose = matrix.T@matrix
print(dotProductOfAATraspose)

eigvalues, eigvectors = np.linalg.eig(matrix)
print(eigvalues)
print(eigvectors)

[[3 0]
 [4 5]]
[[3 4]
 [0 5]]
[[3 0]
 [4 5]]
15.0
15.0
[[ 9 12]
 [12 41]]
[3. 5.]
[[1.         0.89442719]
 [0.         0.4472136 ]]


***CLass 2: Matrix Operations***

In [ ]:
import numpy as np
A = np.array([[3,4],[0,5]])
B = np.transpose(A)
print(B)

C = A@B
print(C)

D=B@A
print(D)

eigvalues, eigectors = np.linalg.eig(C)
print(eigvalues)
print(eigectors)


[[3 0]
 [4 5]]
[[25 20]
 [20 25]]
[[ 9 12]
 [12 41]]
[45.  5.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [ ]:
import numpy as np

K = np.array([10, 20, 30, 40, 50])
m = np.insert(K,2, 60)
print(m)
N = m.reshape(1,6)
J = m.reshape(6,1)
print(N)
print(J)

[10 20 60 30 40 50]
[[10 20 60 30 40 50]]
[[10]
 [20]
 [60]
 [30]
 [40]
 [50]]


***User defined functions***

In [ ]:
def vote():
  age = int(input("Enter your age: "))
  if age >= 18:
    print("You are eligible to vote")
  else:
    print("You are not eligible to vote")

vote()

Enter your age: 7
You are not eligible to vote


In [ ]:
import pandas as pd
data = pd.read_csv("Jumaste.csv")
data.shape()
print(data)

FileNotFoundError: [Errno 2] No such file or directory: 'Jumaste.csv'